name: Update external resources
on:
  schedule:
    # Run every day at 00:00
    - cron:  '0 0 * * *'

jobs:
  update_external_resources:
    name: Update external resources
    runs-on: ubuntu-latest
    steps:
      # Scheduled workflows run on the default branch
      - name: Checkout external-resources branch
        uses: actions/checkout@v2
        with:
          ref: external-resources
      - name: Install environment
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: covid19
          environment-file: environment.yml
          auto-activate-base: false
          miniconda-version: 'latest'
      - name: Update JHU CSSE data
        shell: bash --login {0}
        run: bash csse/generate-csse-stats.sh
      - name: Update EBM Data Lab data
        shell: bash --login {0}
        run: bash ebmdatalab/generate-ebmdatalab-stats.sh
      - name: Commit JHU CSSE and EBM Data Lab figures
        uses: EndBug/add-and-commit@v4
        with:
          add: '*/*.png */*.svg'
          author_name: GitHub Actions
          author_email: actions@github.com
          message: 'Update JHU CSSE and EBM Data Lab figures'
          ref: external-resources
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update figure versions
        shell: bash --login {0}
        run: bash version-figures.sh
      - name: Commit JHU CSSE and EBM Data Lab statistics
        uses: EndBug/add-and-commit@v4
        with:
          add: '*/*.json'
          author_name: GitHub Actions
          author_email: actions@github.com
          message: 'Update JHU CSSE and EBM Data Lab statistics'
          ref: external-resources
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
